---

- name: Make sure OpenSSH is installed
  pacman:
    name: openssh
    state: present

- name: Write SSH client config
  template:
    src: "templates/ssh_config.j2"
    dest: "/etc/ssh/ssh_config"

- name: Write SSH server config
  template:
    src: "templates/sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
  notify: restart_sshd

- name: Make sure SSH server is started and enabled
  systemd:
    name: sshd.service
    state: started
    enabled: yes